### PR TITLE
Deprecate the LazyLoadingProperties trait

### PR DESCRIPTION
**Pull request by Braunson**
Ref: https://github.com/oliverklee/ext-oelib/issues/1235

Removes the trait and tests for the trait, moves the logic into the Model where it's solely used.

#hacktoberfest

### CODE REVIEW

**Review by oliverklee — CHANGES_REQUESTED** [review]
Thanks for your contribution!

You're a bit fast, though. ;-)

The referenced ticket is only about deprecating the trait, not removing it. (My deprecation policy usually is to first mark functionality as `@deprecated` in a release and then remove it in the next breaking release according to [semantic versioning](https://semver.org/), which in this case would be 6.0.)

So could you please instead mark the trait as `@deprecated will be removed in oelib 6` and also add a changelog entry for the deprecation? Thanks!

**Comment by Braunson** [comment]
@oliverklee Whoops, getting ahead of myself. Updated, thanks!

**Review by oliverklee — APPROVED** [review]
Looks good, thanks!

**Comment by oliverklee** [comment]
Thanks a lot for your contribution, @Braunson, and congratulations for your first merged PR in my TYPO3 extensions! :heart:

I'd like to give you some pointers that might help you in your future open source contribution adventures:

## Git branches and PRs

I strongly recommend creating a separate branch for each PR, and not working directly on the default branch (which usually is `main` or `master`) of the repository.  If you work on the default branch, you can have only one PR per repository at a time, and updating your fork will become a real pain. GitHub has some documentation on [forks](https://docs.github.com/en/get-started/quickstart/fork-a-repo) and [pull requests](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/about-pull-requests) that probably will help.

## Commit messages

I can highly recommend [this blog post](https://cbea.ms/git-commit/) on writing better git commit messages. (Particularly, please use the imperative voice.)

Also, when contributing to projects, I propose having a look at the existing git history to learn about the project's specific git commit message conventions. For example, in my projects, I use prefixes like `[TASK]` (adopted from the TYPO3 Core)  to indicate the type of change, and I use `Fixes #1233` to mark which issues a PR should close.

## Code style and CI

When you are a new contributor to a project, the continuous integration (CI) jobs are not run by default (to avoid misuse), and a maintainer needs to activate them for your PR. This means that you'll not get fast feedback from things the CI jobs check, e.g., code style, usage of types, and unit tests.

To get quick feedback on possible changes in your PR that might break the build, I strongly recommend running at least the static checks (code style etc.) locally before creating a PR. In my oelib and seminars extensions, you can run all static checks with a composer script: `composer ci static`. You can also run `composer` to get a list of all available scripts. (Note: You'll need to have the dependencies installed first using `composer install` or `composer update`.)

**Pull request merged**
