### PR TITLE
[WIP][CLEANUP] Migrate global classes to proper namespace

### PR DESCRIPTION
**Pull request by Konafets**
Part of #398

### CODE REVIEW

**Review by oliverklee — CHANGES_REQUESTED** [review]
All the global classes need to go into subnamespaces. Please see the tests namespace/folder structure about what should go where.

**Comment by oliverklee** [comment]
(And please let's have one PR per sub-namespace, if possible.)

**Comment by oliverklee** [comment]
I think the `TemplateHelper` needs some bug fixes before it can be namespaced. I will take care of this in #435.

**Comment by Konafets** [comment]
How about this separation?

This is a draft. The namespaces are correct yet.

```php
    // Authentication
    'Tx_Oelib_BackEndLoginManager' => \OliverKlee\Oelib\BackEndLoginManager::class,
    'Tx_Oelib_FrontEndLoginManager' => \OliverKlee\Oelib\FrontEndLoginManager::class,

    // Configuration
    'Tx_Oelib_ConfigCheck' => \OliverKlee\Oelib\ConfigCheck::class,
    'Tx_Oelib_Configuration' => \OliverKlee\Oelib\Configuration::class,
    'Tx_Oelib_ConfigurationProxy' => \OliverKlee\Oelib\ConfigurationProxy::class,
    'Tx_Oelib_ConfigurationRegistry' => \OliverKlee\Oelib\ConfigurationRegistry::class,
    'Tx_Oelib_PageFinder' => \OliverKlee\Oelib\PageFinder::class,

    // DataStructures
    'Tx_Oelib_Object' => \OliverKlee\Oelib\AbstractObjectWithAccessors::class,
    'Tx_Oelib_PublicObject' => \OliverKlee\Oelib\AbstractObjectWithPublicAccessors::class,
    'Tx_Oelib_List' => \OliverKlee\Oelib\Collection::class,
    'Tx_Oelib_IdentityMap' => \OliverKlee\Oelib\IdentityMap::class,

    // DB 
    'Tx_Oelib_Db' => \OliverKlee\Oelib\Db::class,
    
    // Http
    'Tx_Oelib_AbstractHeaderProxy' => \OliverKlee\Oelib\Http\AbstractHeaderProxy::class,
    'Tx_Oelib_HeaderCollector' => \OliverKlee\Oelib\Http\HeaderCollector::class,
    'Tx_Oelib_HeaderProxyFactory' => \OliverKlee\Oelib\Http\HeaderProxyFactory::class,
    'Tx_Oelib_RealHeaderProxy' => \OliverKlee\Oelib\Http\RealHeaderProxy::class,
    
    // Language
    'Tx_Oelib_SalutationSwitcher' => \OliverKlee\Oelib\SalutationSwitcher::class,
    'Tx_Oelib_Translator' => \OliverKlee\Oelib\Translator::class,
    'Tx_Oelib_TranslatorRegistry' => \OliverKlee\Oelib\TranslatorRegistry::class,

    // Mail
    'Tx_Oelib_AbstractMailer' => \OliverKlee\Oelib\AbstractMailer::class,
    'Tx_Oelib_Attachment' => \OliverKlee\Oelib\Attachment::class,
    'Tx_Oelib_EmailCollector' => \OliverKlee\Oelib\EmailCollector::class,
    'Tx_Oelib_Mail' => \OliverKlee\Oelib\Mail\Mail::class,
    'Tx_Oelib_MailerFactory' => \OliverKlee\Oelib\MailerFactory::class,
    'Tx_Oelib_RealMailer' => \OliverKlee\Oelib\RealMailer::class,

    // Model
    'Tx_Oelib_Model' => \OliverKlee\Oelib\AbstractModel::class,

    // Session
    'Tx_Oelib_FakeSession' => \OliverKlee\Oelib\FakeSession::class,
    'Tx_Oelib_Session' => \OliverKlee\Oelib\Session::class,

    // Templating
    'Tx_Oelib_Template' => \OliverKlee\Oelib\Template::class,
    'Tx_Oelib_TemplateHelper' => \OliverKlee\Oelib\TemplateHelper::class,
    'Tx_Oelib_TemplateRegistry' => \OliverKlee\Oelib\TemplateRegistry::class,

    // Testing
    'Tx_Oelib_TestingFramework' => \OliverKlee\Oelib\TestingFramework::class,
    'Tx_Oelib_TestingFrameworkCleanup' => \OliverKlee\Oelib\TestingFrameworkCleanup::class,
    
    // Time
    'Tx_Oelib_Time' => \OliverKlee\Oelib\Time::class,
```

**Comment by oliverklee** [comment]
Sounds like a good plan. Let's go for it!

(And please let's do the templating classes last so I can fix the bug in `TemplateHelper` first.)

**Pull request closed without merging**
